### ISSUE TITLE
No working on mac

### ISSUE THREAD

**Issue by horaciogarza** [tomakita/Colorful.Console#22] opened 2017-03-19 01:59 UTC
![image](https://cloud.githubusercontent.com/assets/6968362/24077518/5384e0c4-0c15-11e7-8434-fe14191e0381.png)

**Comment by horaciogarza** [comment] 2017-03-19 02:01
```
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Colorful.Console' threw an exception. ---> System.EntryPointNotFoundException: GetStdHandle
  at (wrapper managed-to-native) Colorful.ColorMapper:GetStdHandle (int)
  at Colorful.ColorMapper.GetBufferColors () [0x00007] in <f4abfa4d1efe4e7a96624e6ac7a975e0>:0 
  at Colorful.Console..cctor () [0x0016e] in <f4abfa4d1efe4e7a96624e6ac7a975e0>:0 
   --- End of inner exception stack trace ---
  at AutomatedTask.MainClass.Main (System.String[] args) [0x0001f] in /Users/horaciogarza/Projects/AutomatedTask/AutomatedTask/Program.cs:17 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Colorful.Console' threw an exception. ---> System.EntryPointNotFoundException: GetStdHandle
  at (wrapper managed-to-native) Colorful.ColorMapper:GetStdHandle (int)
  at Colorful.ColorMapper.GetBufferColors () [0x00007] in <f4abfa4d1efe4e7a96624e6ac7a975e0>:0 
  at Colorful.Console..cctor () [0x0016e] in <f4abfa4d1efe4e7a96624e6ac7a975e0>:0 
   --- End of inner exception stack trace ---
  at AutomatedTask.MainClass.Main (System.String[] args) [0x0001f] in /Users/horaciogarza/Projects/AutomatedTask/AutomatedTask/Program.cs:17 

Press any key to continue...
```

**Comment by tomakita** [comment] 2017-03-19 05:31
Thanks for reporting this issue, and thanks for sharing the stack trace.  This seems to be a duplicate of https://github.com/tomakita/Colorful.Console/issues/13, so I'm going to close this.  Cross-platform support has been trickier than expected, and unfortunately, I don't have the time that I would like to work on it at the moment.

Thanks again, and let me know if you think this should be reopened!

**Closed by tomakita** 2017-03-19 05:31 UTC

**Comment by jrr** [comment] 2017-05-27 03:29
Following https://github.com/tomakita/Colorful.Console/issues/13, non-Windows ports would need to avoid the kernel32 DLLImports in Colormapper: https://github.com/tomakita/Colorful.Console/blob/5c45c54ad346a31a2aefe406c5310d673042e14e/src/Colorful.Console/ColorMapper.cs#L62
