### ISSUE TITLE
Unfortunately, Colorful.Console does NOT render correctly on Mac

### ISSUE THREAD

**Issue by jasonvogel** [tomakita/Colorful.Console#47] opened 2018-02-22 05:59 UTC
Even the simplest test fails to render correctly on the Mac. Standard Console.ForegroundColor = ConsoleColor.Red works, but not the Colorful equivalent.

I was really excited when I first found this library.

**Comment by AlexejheroYTB** [comment] 2018-08-19 17:42
Duplicate of #46

**Comment by tomakita** [comment] 2019-06-22 16:01
Thanks for the report.  Closing as duplicate, for now.

**Closed by tomakita** 2019-06-22 16:01 UTC
Labels: duplicate
