### ISSUE TITLE
Horizontal color alternation?

### ISSUE THREAD

**Issue by hmemcpy** [tomakita/Colorful.Console#6] opened 2016-02-24 19:40 UTC
Hi!

Love your library! Thank you very much for making it!
I'd like to print something in ASCII (e.g. "mySign"), with the word "my" painted in one color, and the word "Sign" in another.
Is it something I should be able to do with `PatternBasedColorAlternator`? Because I'm afraid I can't get it to work... I tried:

```csharp
   Colorful.Console.WriteAsciiAlternating("mySign", 
                new PatternBasedColorAlternator<string>(new TextPatternCollection(new[] { "my", "Sign" }), Color.Yellow, Color.Orange));
```

but that only outputs it in yellow... I must be holding it wrong.

Any suggestions?

**Comment by tomakita** [comment] 2016-02-25 02:46
Hi Igal,

Thanks for the kind words, and thanks for bringing this to my attention!  It looks like this is a bug.  I can see where the problem is, but it'll take me some time to fix.  I'll try to get to it this weekend, and will keep this thread updated either way.

Thanks again,

Tom

**Comment by tomakita** [comment] 2016-02-27 15:33
Working on this now.  Should be done by end of weekend.

**Comment by hmemcpy** [comment] 2016-02-27 19:39
Thanks so much, Tom!

Please let me know if I can help somehow :)

**Comment by tomakita** [comment] 2016-02-28 20:47
Making progress:

![igal](https://cloud.githubusercontent.com/assets/8643072/13381778/f2b67d8a-de29-11e5-81a8-b95d3756265c.png)

Should be done by the end of the day!

**Comment by tomakita** [comment] 2016-02-28 22:09
Ok, I've just committed all of the changes, and released a new version of the NuGet package (version 1.0.5) -- this should be fixed now.  See below for usage:

    StyleSheet styleSheet = new StyleSheet(Color.LightGoldenrodYellow);
    styleSheet.AddStyle("Sign", Color.PaleGreen);
    Console.WriteAsciiStyled("mySign", styleSheet);

Let me know if this isn't what you needed (or if it's broken, etc.).  Thanks again for finding this bug!

**Closed** 2016-02-28 22:09 UTC
Labels: bug

**Comment by hmemcpy** [comment] 2016-02-29 06:58
Thank you so very much! Looks great, can't wait to try it in my console app :)

**Comment by hmemcpy** [comment] 2016-02-29 19:55
Sorry for the spam, just wanted to say it works great! Thanks a lot for fixing this :)

**Comment by tomakita** [comment] 2016-02-29 22:45
No problem, great to hear that it's working!
